
/* This file is generated by applying the dr.xsl stylesheet to the dr.xml
 * description file. DO NOT EDIT !!! */

#include "config.h"

#include <stdio.h>
#include <stdbool.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>

#if defined(HAVE_INTTYPES_H)
#include <inttypes.h>
#elif defined(HAVE_STDINT_H)
#include <stdint.h>
#endif

/* the libdvbpsi distribution defines DVBPSI_DIST */
#ifdef DVBPSI_DIST
#include "../src/dvbpsi.h"
#include "../src/descriptor.h"
#include "../src/descriptors/dr.h"
#else
#include <dvbpsi/dvbpsi.h>
#include <dvbpsi/descriptor.h>
#include <dvbpsi/dr.h>
#endif

#include "test_dr.h"

  
/* video stream (b_mpeg2 = false) */
static int main_mpeg_vstream_1(void)
{
  BOZO_VARS(mpeg_vstream);
  BOZO_START(video stream (b_mpeg2 = false));

  
  /* check b_multiple_frame_rate */
  BOZO_init_boolean(b_multiple_frame_rate, 0);
  BOZO_init_integer(i_frame_rate_code, 0);
  s_decoded.b_mpeg2 = false;
  BOZO_init_boolean(b_constrained_parameter, 0);
  BOZO_init_boolean(b_still_picture, 0);
  BOZO_begin_boolean(b_multiple_frame_rate)
    BOZO_DOJOB(mpeg_vstream);
    BOZO_check_boolean(b_multiple_frame_rate)
    BOZO_CLEAN();
  BOZO_end_boolean(b_multiple_frame_rate)

  /* check i_frame_rate_code */
  BOZO_init_boolean(b_multiple_frame_rate, 0);
  BOZO_init_integer(i_frame_rate_code, 0);
  s_decoded.b_mpeg2 = false;
  BOZO_init_boolean(b_constrained_parameter, 0);
  BOZO_init_boolean(b_still_picture, 0);
  BOZO_begin_integer(i_frame_rate_code, 4)
    BOZO_DOJOB(mpeg_vstream);
    BOZO_check_integer(i_frame_rate_code, 4)
    BOZO_CLEAN();
  BOZO_end_integer(i_frame_rate_code, 4)

  /* check b_constrained_parameter */
  BOZO_init_boolean(b_multiple_frame_rate, 0);
  BOZO_init_integer(i_frame_rate_code, 0);
  s_decoded.b_mpeg2 = false;
  BOZO_init_boolean(b_constrained_parameter, 0);
  BOZO_init_boolean(b_still_picture, 0);
  BOZO_begin_boolean(b_constrained_parameter)
    BOZO_DOJOB(mpeg_vstream);
    BOZO_check_boolean(b_constrained_parameter)
    BOZO_CLEAN();
  BOZO_end_boolean(b_constrained_parameter)

  /* check b_still_picture */
  BOZO_init_boolean(b_multiple_frame_rate, 0);
  BOZO_init_integer(i_frame_rate_code, 0);
  s_decoded.b_mpeg2 = false;
  BOZO_init_boolean(b_constrained_parameter, 0);
  BOZO_init_boolean(b_still_picture, 0);
  BOZO_begin_boolean(b_still_picture)
    BOZO_DOJOB(mpeg_vstream);
    BOZO_check_boolean(b_still_picture)
    BOZO_CLEAN();
  BOZO_end_boolean(b_still_picture)


  BOZO_END(video stream (b_mpeg2 = false));

  return i_err;
}

/* video stream (b_mpeg2 = true) */
static int main_mpeg_vstream_2(void)
{
  BOZO_VARS(mpeg_vstream);
  BOZO_START(video stream (b_mpeg2 = true));

  
  /* check b_multiple_frame_rate */
  BOZO_init_boolean(b_multiple_frame_rate, 0);
  BOZO_init_integer(i_frame_rate_code, 0);
  s_decoded.b_mpeg2 = true;
  BOZO_init_boolean(b_constrained_parameter, 0);
  BOZO_init_boolean(b_still_picture, 0);
  BOZO_init_integer(i_profile_level_indication, 0);
  BOZO_init_integer(i_chroma_format, 0);
  BOZO_init_boolean(b_frame_rate_extension, 0);
  BOZO_begin_boolean(b_multiple_frame_rate)
    BOZO_DOJOB(mpeg_vstream);
    BOZO_check_boolean(b_multiple_frame_rate)
    BOZO_CLEAN();
  BOZO_end_boolean(b_multiple_frame_rate)

  /* check i_frame_rate_code */
  BOZO_init_boolean(b_multiple_frame_rate, 0);
  BOZO_init_integer(i_frame_rate_code, 0);
  s_decoded.b_mpeg2 = true;
  BOZO_init_boolean(b_constrained_parameter, 0);
  BOZO_init_boolean(b_still_picture, 0);
  BOZO_init_integer(i_profile_level_indication, 0);
  BOZO_init_integer(i_chroma_format, 0);
  BOZO_init_boolean(b_frame_rate_extension, 0);
  BOZO_begin_integer(i_frame_rate_code, 4)
    BOZO_DOJOB(mpeg_vstream);
    BOZO_check_integer(i_frame_rate_code, 4)
    BOZO_CLEAN();
  BOZO_end_integer(i_frame_rate_code, 4)

  /* check b_constrained_parameter */
  BOZO_init_boolean(b_multiple_frame_rate, 0);
  BOZO_init_integer(i_frame_rate_code, 0);
  s_decoded.b_mpeg2 = true;
  BOZO_init_boolean(b_constrained_parameter, 0);
  BOZO_init_boolean(b_still_picture, 0);
  BOZO_init_integer(i_profile_level_indication, 0);
  BOZO_init_integer(i_chroma_format, 0);
  BOZO_init_boolean(b_frame_rate_extension, 0);
  BOZO_begin_boolean(b_constrained_parameter)
    BOZO_DOJOB(mpeg_vstream);
    BOZO_check_boolean(b_constrained_parameter)
    BOZO_CLEAN();
  BOZO_end_boolean(b_constrained_parameter)

  /* check b_still_picture */
  BOZO_init_boolean(b_multiple_frame_rate, 0);
  BOZO_init_integer(i_frame_rate_code, 0);
  s_decoded.b_mpeg2 = true;
  BOZO_init_boolean(b_constrained_parameter, 0);
  BOZO_init_boolean(b_still_picture, 0);
  BOZO_init_integer(i_profile_level_indication, 0);
  BOZO_init_integer(i_chroma_format, 0);
  BOZO_init_boolean(b_frame_rate_extension, 0);
  BOZO_begin_boolean(b_still_picture)
    BOZO_DOJOB(mpeg_vstream);
    BOZO_check_boolean(b_still_picture)
    BOZO_CLEAN();
  BOZO_end_boolean(b_still_picture)

  /* check i_profile_level_indication */
  BOZO_init_boolean(b_multiple_frame_rate, 0);
  BOZO_init_integer(i_frame_rate_code, 0);
  s_decoded.b_mpeg2 = true;
  BOZO_init_boolean(b_constrained_parameter, 0);
  BOZO_init_boolean(b_still_picture, 0);
  BOZO_init_integer(i_profile_level_indication, 0);
  BOZO_init_integer(i_chroma_format, 0);
  BOZO_init_boolean(b_frame_rate_extension, 0);
  BOZO_begin_integer(i_profile_level_indication, 8)
    BOZO_DOJOB(mpeg_vstream);
    BOZO_check_integer(i_profile_level_indication, 8)
    BOZO_CLEAN();
  BOZO_end_integer(i_profile_level_indication, 8)

  /* check i_chroma_format */
  BOZO_init_boolean(b_multiple_frame_rate, 0);
  BOZO_init_integer(i_frame_rate_code, 0);
  s_decoded.b_mpeg2 = true;
  BOZO_init_boolean(b_constrained_parameter, 0);
  BOZO_init_boolean(b_still_picture, 0);
  BOZO_init_integer(i_profile_level_indication, 0);
  BOZO_init_integer(i_chroma_format, 0);
  BOZO_init_boolean(b_frame_rate_extension, 0);
  BOZO_begin_integer(i_chroma_format, 2)
    BOZO_DOJOB(mpeg_vstream);
    BOZO_check_integer(i_chroma_format, 2)
    BOZO_CLEAN();
  BOZO_end_integer(i_chroma_format, 2)

  /* check b_frame_rate_extension */
  BOZO_init_boolean(b_multiple_frame_rate, 0);
  BOZO_init_integer(i_frame_rate_code, 0);
  s_decoded.b_mpeg2 = true;
  BOZO_init_boolean(b_constrained_parameter, 0);
  BOZO_init_boolean(b_still_picture, 0);
  BOZO_init_integer(i_profile_level_indication, 0);
  BOZO_init_integer(i_chroma_format, 0);
  BOZO_init_boolean(b_frame_rate_extension, 0);
  BOZO_begin_boolean(b_frame_rate_extension)
    BOZO_DOJOB(mpeg_vstream);
    BOZO_check_boolean(b_frame_rate_extension)
    BOZO_CLEAN();
  BOZO_end_boolean(b_frame_rate_extension)


  BOZO_END(video stream (b_mpeg2 = true));

  return i_err;
}

/* audio stream */
static int main_mpeg_astream_(void)
{
  BOZO_VARS(mpeg_astream);
  BOZO_START(audio stream);

  
  /* check b_free_format */
  BOZO_init_boolean(b_free_format, 0);
  BOZO_init_integer(i_id, 0);
  BOZO_init_integer(i_layer, 0);
  BOZO_begin_boolean(b_free_format)
    BOZO_DOJOB(mpeg_astream);
    BOZO_check_boolean(b_free_format)
    BOZO_CLEAN();
  BOZO_end_boolean(b_free_format)

  /* check i_id */
  BOZO_init_boolean(b_free_format, 0);
  BOZO_init_integer(i_id, 0);
  BOZO_init_integer(i_layer, 0);
  BOZO_begin_integer(i_id, 1)
    BOZO_DOJOB(mpeg_astream);
    BOZO_check_integer(i_id, 1)
    BOZO_CLEAN();
  BOZO_end_integer(i_id, 1)

  /* check i_layer */
  BOZO_init_boolean(b_free_format, 0);
  BOZO_init_integer(i_id, 0);
  BOZO_init_integer(i_layer, 0);
  BOZO_begin_integer(i_layer, 2)
    BOZO_DOJOB(mpeg_astream);
    BOZO_check_integer(i_layer, 2)
    BOZO_CLEAN();
  BOZO_end_integer(i_layer, 2)


  BOZO_END(audio stream);

  return i_err;
}

/* hierarchy */
static int main_mpeg_hierarchy_(void)
{
  BOZO_VARS(mpeg_hierarchy);
  BOZO_START(hierarchy);

  
  /* check i_h_type */
  BOZO_init_integer(i_h_type, 0);
  BOZO_init_integer(i_h_layer_index, 0);
  BOZO_init_integer(i_h_embedded_layer, 0);
  BOZO_init_integer(i_h_priority, 0);
  BOZO_begin_integer(i_h_type, 4)
    BOZO_DOJOB(mpeg_hierarchy);
    BOZO_check_integer(i_h_type, 4)
    BOZO_CLEAN();
  BOZO_end_integer(i_h_type, 4)

  /* check i_h_layer_index */
  BOZO_init_integer(i_h_type, 0);
  BOZO_init_integer(i_h_layer_index, 0);
  BOZO_init_integer(i_h_embedded_layer, 0);
  BOZO_init_integer(i_h_priority, 0);
  BOZO_begin_integer(i_h_layer_index, 6)
    BOZO_DOJOB(mpeg_hierarchy);
    BOZO_check_integer(i_h_layer_index, 6)
    BOZO_CLEAN();
  BOZO_end_integer(i_h_layer_index, 6)

  /* check i_h_embedded_layer */
  BOZO_init_integer(i_h_type, 0);
  BOZO_init_integer(i_h_layer_index, 0);
  BOZO_init_integer(i_h_embedded_layer, 0);
  BOZO_init_integer(i_h_priority, 0);
  BOZO_begin_integer(i_h_embedded_layer, 6)
    BOZO_DOJOB(mpeg_hierarchy);
    BOZO_check_integer(i_h_embedded_layer, 6)
    BOZO_CLEAN();
  BOZO_end_integer(i_h_embedded_layer, 6)

  /* check i_h_priority */
  BOZO_init_integer(i_h_type, 0);
  BOZO_init_integer(i_h_layer_index, 0);
  BOZO_init_integer(i_h_embedded_layer, 0);
  BOZO_init_integer(i_h_priority, 0);
  BOZO_begin_integer(i_h_priority, 6)
    BOZO_DOJOB(mpeg_hierarchy);
    BOZO_check_integer(i_h_priority, 6)
    BOZO_CLEAN();
  BOZO_end_integer(i_h_priority, 6)


  BOZO_END(hierarchy);

  return i_err;
}

/* registration */
static int main_mpeg_registration_(void)
{
  BOZO_VARS(mpeg_registration);
  BOZO_START(registration);

  
  /* check i_format_identifier */
  s_decoded.i_additional_length = 0;
  BOZO_init_integer(i_format_identifier, 0);
  BOZO_begin_integer(i_format_identifier, 32)
    BOZO_DOJOB(mpeg_registration);
    BOZO_check_integer(i_format_identifier, 32)
    BOZO_CLEAN();
  BOZO_end_integer(i_format_identifier, 32)


  BOZO_END(registration);

  return i_err;
}

/* data stream alignment */
static int main_mpeg_ds_alignment_(void)
{
  BOZO_VARS(mpeg_ds_alignment);
  BOZO_START(data stream alignment);

  
  /* check i_alignment_type */
  BOZO_init_integer(i_alignment_type, 0);
  BOZO_begin_integer(i_alignment_type, 8)
    BOZO_DOJOB(mpeg_ds_alignment);
    BOZO_check_integer(i_alignment_type, 8)
    BOZO_CLEAN();
  BOZO_end_integer(i_alignment_type, 8)


  BOZO_END(data stream alignment);

  return i_err;
}

/* target background grid */
static int main_mpeg_target_bg_grid_(void)
{
  BOZO_VARS(mpeg_target_bg_grid);
  BOZO_START(target background grid);

  
  /* check i_horizontal_size */
  BOZO_init_integer(i_horizontal_size, 0);
  BOZO_init_integer(i_vertical_size, 0);
  BOZO_init_integer(i_pel_aspect_ratio, 0);
  BOZO_begin_integer(i_horizontal_size, 14)
    BOZO_DOJOB(mpeg_target_bg_grid);
    BOZO_check_integer(i_horizontal_size, 14)
    BOZO_CLEAN();
  BOZO_end_integer(i_horizontal_size, 14)

  /* check i_vertical_size */
  BOZO_init_integer(i_horizontal_size, 0);
  BOZO_init_integer(i_vertical_size, 0);
  BOZO_init_integer(i_pel_aspect_ratio, 0);
  BOZO_begin_integer(i_vertical_size, 14)
    BOZO_DOJOB(mpeg_target_bg_grid);
    BOZO_check_integer(i_vertical_size, 14)
    BOZO_CLEAN();
  BOZO_end_integer(i_vertical_size, 14)

  /* check i_pel_aspect_ratio */
  BOZO_init_integer(i_horizontal_size, 0);
  BOZO_init_integer(i_vertical_size, 0);
  BOZO_init_integer(i_pel_aspect_ratio, 0);
  BOZO_begin_integer(i_pel_aspect_ratio, 4)
    BOZO_DOJOB(mpeg_target_bg_grid);
    BOZO_check_integer(i_pel_aspect_ratio, 4)
    BOZO_CLEAN();
  BOZO_end_integer(i_pel_aspect_ratio, 4)


  BOZO_END(target background grid);

  return i_err;
}

/* video window */
static int main_mpeg_vwindow_(void)
{
  BOZO_VARS(mpeg_vwindow);
  BOZO_START(video window);

  
  /* check i_horizontal_offset */
  BOZO_init_integer(i_horizontal_offset, 0);
  BOZO_init_integer(i_vertical_offset, 0);
  BOZO_init_integer(i_window_priority, 0);
  BOZO_begin_integer(i_horizontal_offset, 14)
    BOZO_DOJOB(mpeg_vwindow);
    BOZO_check_integer(i_horizontal_offset, 14)
    BOZO_CLEAN();
  BOZO_end_integer(i_horizontal_offset, 14)

  /* check i_vertical_offset */
  BOZO_init_integer(i_horizontal_offset, 0);
  BOZO_init_integer(i_vertical_offset, 0);
  BOZO_init_integer(i_window_priority, 0);
  BOZO_begin_integer(i_vertical_offset, 14)
    BOZO_DOJOB(mpeg_vwindow);
    BOZO_check_integer(i_vertical_offset, 14)
    BOZO_CLEAN();
  BOZO_end_integer(i_vertical_offset, 14)

  /* check i_window_priority */
  BOZO_init_integer(i_horizontal_offset, 0);
  BOZO_init_integer(i_vertical_offset, 0);
  BOZO_init_integer(i_window_priority, 0);
  BOZO_begin_integer(i_window_priority, 4)
    BOZO_DOJOB(mpeg_vwindow);
    BOZO_check_integer(i_window_priority, 4)
    BOZO_CLEAN();
  BOZO_end_integer(i_window_priority, 4)


  BOZO_END(video window);

  return i_err;
}

/* conditional access */
static int main_mpeg_ca_(void)
{
  BOZO_VARS(mpeg_ca);
  BOZO_START(conditional access);

  
  /* check i_ca_system_id */
  s_decoded.i_private_length = 0;
  BOZO_init_integer(i_ca_system_id, 0);
  BOZO_init_integer(i_ca_pid, 0);
  BOZO_init_array(i_private_length);
  BOZO_begin_integer(i_ca_system_id, 16)
    BOZO_DOJOB(mpeg_ca);
    BOZO_check_integer(i_ca_system_id, 16)
    BOZO_CLEAN();
  BOZO_end_integer(i_ca_system_id, 16)

  /* check i_ca_pid */
  s_decoded.i_private_length = 0;
  BOZO_init_integer(i_ca_system_id, 0);
  BOZO_init_integer(i_ca_pid, 0);
  BOZO_init_array(i_private_length);
  BOZO_begin_integer(i_ca_pid, 13)
    BOZO_DOJOB(mpeg_ca);
    BOZO_check_integer(i_ca_pid, 13)
    BOZO_CLEAN();
  BOZO_end_integer(i_ca_pid, 13)

  /* check i_private_data */
  s_decoded.i_private_length = 0;
  BOZO_init_integer(i_ca_system_id, 0);
  BOZO_init_integer(i_ca_pid, 0);
  BOZO_init_array(i_private_length);
  BOZO_begin_array(i_private_data)
  BOZO_loop_array_begin(i_private_data, i_private_length, 0)
    BOZO_DOJOB(mpeg_ca);
    BOZO_check_array_begin(i_private_data, i_private_length)
    BOZO_check_array_gen(i_private_data, i_private_length)
    BOZO_CLEAN();
  BOZO_loop_array_end(i_private_data, ARRAY_SIZE(s_decoded.i_private_data))
  BOZO_end_array


  BOZO_END(conditional access);

  return i_err;
}

/* ISO 639 language */
static int main_mpeg_iso639_(void)
{
  BOZO_VARS(mpeg_iso639);
  BOZO_START(ISO 639 language);

  
  /* check code */
  BOZO_init_array(i_code_count);
  BOZO_begin_array(code)
  BOZO_loop_array_begin(code, i_code_count, 1)
    BOZO_DOJOB(mpeg_iso639);
    BOZO_check_array_begin(code, i_code_count)
    BOZO_check_array_gen(code, i_code_count)
    BOZO_CLEAN();
  BOZO_loop_array_end(code, ARRAY_SIZE(s_decoded.code))
  BOZO_end_array


  BOZO_END(ISO 639 language);

  return i_err;
}

/* system clock */
static int main_mpeg_system_clock_(void)
{
  BOZO_VARS(mpeg_system_clock);
  BOZO_START(system clock);

  
  /* check b_external_clock_ref */
  BOZO_init_boolean(b_external_clock_ref, 0);
  BOZO_init_integer(i_clock_accuracy_integer, 0);
  BOZO_init_integer(i_clock_accuracy_exponent, 0);
  BOZO_begin_boolean(b_external_clock_ref)
    BOZO_DOJOB(mpeg_system_clock);
    BOZO_check_boolean(b_external_clock_ref)
    BOZO_CLEAN();
  BOZO_end_boolean(b_external_clock_ref)

  /* check i_clock_accuracy_integer */
  BOZO_init_boolean(b_external_clock_ref, 0);
  BOZO_init_integer(i_clock_accuracy_integer, 0);
  BOZO_init_integer(i_clock_accuracy_exponent, 0);
  BOZO_begin_integer(i_clock_accuracy_integer, 6)
    BOZO_DOJOB(mpeg_system_clock);
    BOZO_check_integer(i_clock_accuracy_integer, 6)
    BOZO_CLEAN();
  BOZO_end_integer(i_clock_accuracy_integer, 6)

  /* check i_clock_accuracy_exponent */
  BOZO_init_boolean(b_external_clock_ref, 0);
  BOZO_init_integer(i_clock_accuracy_integer, 0);
  BOZO_init_integer(i_clock_accuracy_exponent, 0);
  BOZO_begin_integer(i_clock_accuracy_exponent, 3)
    BOZO_DOJOB(mpeg_system_clock);
    BOZO_check_integer(i_clock_accuracy_exponent, 3)
    BOZO_CLEAN();
  BOZO_end_integer(i_clock_accuracy_exponent, 3)


  BOZO_END(system clock);

  return i_err;
}

/* multiplex buffer utilization */
static int main_mpeg_mx_buff_utilization_(void)
{
  BOZO_VARS(mpeg_mx_buff_utilization);
  BOZO_START(multiplex buffer utilization);

  
  /* check b_mdv_valid */
  BOZO_init_boolean(b_mdv_valid, 0);
  BOZO_init_integer(i_mx_delay_variation, 0);
  BOZO_init_integer(i_mx_strategy, 0);
  BOZO_begin_boolean(b_mdv_valid)
    BOZO_DOJOB(mpeg_mx_buff_utilization);
    BOZO_check_boolean(b_mdv_valid)
    BOZO_CLEAN();
  BOZO_end_boolean(b_mdv_valid)

  /* check i_mx_delay_variation */
  BOZO_init_boolean(b_mdv_valid, 0);
  BOZO_init_integer(i_mx_delay_variation, 0);
  BOZO_init_integer(i_mx_strategy, 0);
  BOZO_begin_integer(i_mx_delay_variation, 15)
    BOZO_DOJOB(mpeg_mx_buff_utilization);
    BOZO_check_integer(i_mx_delay_variation, 15)
    BOZO_CLEAN();
  BOZO_end_integer(i_mx_delay_variation, 15)

  /* check i_mx_strategy */
  BOZO_init_boolean(b_mdv_valid, 0);
  BOZO_init_integer(i_mx_delay_variation, 0);
  BOZO_init_integer(i_mx_strategy, 0);
  BOZO_begin_integer(i_mx_strategy, 3)
    BOZO_DOJOB(mpeg_mx_buff_utilization);
    BOZO_check_integer(i_mx_strategy, 3)
    BOZO_CLEAN();
  BOZO_end_integer(i_mx_strategy, 3)


  BOZO_END(multiplex buffer utilization);

  return i_err;
}

/* copyright */
static int main_mpeg_copyright_(void)
{
  BOZO_VARS(mpeg_copyright);
  BOZO_START(copyright);

  
  /* check i_copyright_identifier */
  s_decoded.i_additional_length = 0;
  BOZO_init_integer(i_copyright_identifier, 0);
  BOZO_init_array(i_additional_length);
  BOZO_begin_integer(i_copyright_identifier, 32)
    BOZO_DOJOB(mpeg_copyright);
    BOZO_check_integer(i_copyright_identifier, 32)
    BOZO_CLEAN();
  BOZO_end_integer(i_copyright_identifier, 32)

  /* check i_additional_info */
  s_decoded.i_additional_length = 0;
  BOZO_init_integer(i_copyright_identifier, 0);
  BOZO_init_array(i_additional_length);
  BOZO_begin_array(i_additional_info)
  BOZO_loop_array_begin(i_additional_info, i_additional_length, 0)
    BOZO_DOJOB(mpeg_copyright);
    BOZO_check_array_begin(i_additional_info, i_additional_length)
    BOZO_check_array_gen(i_additional_info, i_additional_length)
    BOZO_CLEAN();
  BOZO_loop_array_end(i_additional_info, ARRAY_SIZE(s_decoded.i_additional_info))
  BOZO_end_array


  BOZO_END(copyright);

  return i_err;
}

/* maximum bitrate */
static int main_mpeg_max_bitrate_(void)
{
  BOZO_VARS(mpeg_max_bitrate);
  BOZO_START(maximum bitrate);

  
  /* check i_max_bitrate */
  BOZO_init_integer(i_max_bitrate, 0);
  BOZO_begin_integer(i_max_bitrate, 22)
    BOZO_DOJOB(mpeg_max_bitrate);
    BOZO_check_integer(i_max_bitrate, 22)
    BOZO_CLEAN();
  BOZO_end_integer(i_max_bitrate, 22)


  BOZO_END(maximum bitrate);

  return i_err;
}

/* private data indicator */
static int main_mpeg_private_data_(void)
{
  BOZO_VARS(mpeg_private_data);
  BOZO_START(private data indicator);

  
  /* check i_private_data */
  BOZO_init_integer(i_private_data, 0);
  BOZO_begin_integer(i_private_data, 32)
    BOZO_DOJOB(mpeg_private_data);
    BOZO_check_integer(i_private_data, 32)
    BOZO_CLEAN();
  BOZO_end_integer(i_private_data, 32)


  BOZO_END(private data indicator);

  return i_err;
}

/* smoothing buffer */
static int main_mpeg_smoothing_buffer_(void)
{
  BOZO_VARS(mpeg_smoothing_buffer);
  BOZO_START(smoothing buffer);

  
  #define dvbpsi_gen_mpeg_smoothing_buffer_dr(x,y) \
    dvbpsi_gen_mpeg_smoothing_buffer_dr(x)
  
  /* check i_sb_leak_rate */
  BOZO_init_integer(i_sb_leak_rate, 0);
  BOZO_init_integer(i_sb_size, 0);
  BOZO_begin_integer(i_sb_leak_rate, 22)
    BOZO_DOJOB(mpeg_smoothing_buffer);
    BOZO_check_integer(i_sb_leak_rate, 22)
    BOZO_CLEAN();
  BOZO_end_integer(i_sb_leak_rate, 22)

  /* check i_sb_size */
  BOZO_init_integer(i_sb_leak_rate, 0);
  BOZO_init_integer(i_sb_size, 0);
  BOZO_begin_integer(i_sb_size, 22)
    BOZO_DOJOB(mpeg_smoothing_buffer);
    BOZO_check_integer(i_sb_size, 22)
    BOZO_CLEAN();
  BOZO_end_integer(i_sb_size, 22)


  BOZO_END(smoothing buffer);

  return i_err;
}

/* STD */
static int main_mpeg_std_(void)
{
  BOZO_VARS(mpeg_std);
  BOZO_START(STD);

  
  #define dvbpsi_gen_mpeg_std_dr(x,y) \
    dvbpsi_gen_mpeg_std_dr(x)
  
  /* check b_leak_valid_flag */
  BOZO_init_boolean(b_leak_valid_flag, 0);
  BOZO_begin_boolean(b_leak_valid_flag)
    BOZO_DOJOB(mpeg_std);
    BOZO_check_boolean(b_leak_valid_flag)
    BOZO_CLEAN();
  BOZO_end_boolean(b_leak_valid_flag)


  BOZO_END(STD);

  return i_err;
}

/* IBP */
static int main_mpeg_ibp_(void)
{
  BOZO_VARS(mpeg_ibp);
  BOZO_START(IBP);

  
  #define dvbpsi_gen_mpeg_ibp_dr(x,y) \
    dvbpsi_gen_mpeg_ibp_dr(x)
  
  /* check b_closed_gop_flag */
  BOZO_init_boolean(b_closed_gop_flag, 0);
  BOZO_init_boolean(b_identical_gop_flag, 0);
  BOZO_init_integer(i_max_gop_length, 1);
  BOZO_begin_boolean(b_closed_gop_flag)
    BOZO_DOJOB(mpeg_ibp);
    BOZO_check_boolean(b_closed_gop_flag)
    BOZO_CLEAN();
  BOZO_end_boolean(b_closed_gop_flag)

  /* check b_identical_gop_flag */
  BOZO_init_boolean(b_closed_gop_flag, 0);
  BOZO_init_boolean(b_identical_gop_flag, 0);
  BOZO_init_integer(i_max_gop_length, 1);
  BOZO_begin_boolean(b_identical_gop_flag)
    BOZO_DOJOB(mpeg_ibp);
    BOZO_check_boolean(b_identical_gop_flag)
    BOZO_CLEAN();
  BOZO_end_boolean(b_identical_gop_flag)

  /* check i_max_gop_length */
  BOZO_init_boolean(b_closed_gop_flag, 0);
  BOZO_init_boolean(b_identical_gop_flag, 0);
  BOZO_init_integer(i_max_gop_length, 1);
  BOZO_begin_integer(i_max_gop_length, 14)
    BOZO_DOJOB(mpeg_ibp);
    BOZO_check_integer(i_max_gop_length, 14)
    BOZO_CLEAN();
  BOZO_end_integer(i_max_gop_length, 14)


  BOZO_END(IBP);

  return i_err;
}

/* MPEG-4 video */
static int main_mpeg_mpeg4_video_(void)
{
  BOZO_VARS(mpeg_mpeg4_video);
  BOZO_START(MPEG-4 video);

  
  #define dvbpsi_gen_mpeg_mpeg4_video_dr(x,y) \
    dvbpsi_gen_mpeg_mpeg4_video_dr(x)
  
  /* check i_mpeg4_visual_profile_and_level */
  BOZO_init_integer(i_mpeg4_visual_profile_and_level, 0);
  BOZO_begin_integer(i_mpeg4_visual_profile_and_level, 8)
    BOZO_DOJOB(mpeg_mpeg4_video);
    BOZO_check_integer(i_mpeg4_visual_profile_and_level, 8)
    BOZO_CLEAN();
  BOZO_end_integer(i_mpeg4_visual_profile_and_level, 8)


  BOZO_END(MPEG-4 video);

  return i_err;
}

/* MPEG-4 audio */
static int main_mpeg_mpeg4_audio_(void)
{
  BOZO_VARS(mpeg_mpeg4_audio);
  BOZO_START(MPEG-4 audio);

  
  #define dvbpsi_gen_mpeg_mpeg4_audio_dr(x,y) \
    dvbpsi_gen_mpeg_mpeg4_audio_dr(x)
  
  /* check i_mpeg4_audio_profile_and_level */
  BOZO_init_integer(i_mpeg4_audio_profile_and_level, 0);
  BOZO_begin_integer(i_mpeg4_audio_profile_and_level, 8)
    BOZO_DOJOB(mpeg_mpeg4_audio);
    BOZO_check_integer(i_mpeg4_audio_profile_and_level, 8)
    BOZO_CLEAN();
  BOZO_end_integer(i_mpeg4_audio_profile_and_level, 8)


  BOZO_END(MPEG-4 audio);

  return i_err;
}

/* network name */
static int main_dvb_network_name_(void)
{
  BOZO_VARS(dvb_network_name);
  BOZO_START(network name);

  
  /* check i_name_byte */
  BOZO_init_array(i_name_length);
  BOZO_begin_array(i_name_byte)
  BOZO_loop_array_begin(i_name_byte, i_name_length, 0)
    BOZO_DOJOB(dvb_network_name);
    BOZO_check_array_begin(i_name_byte, i_name_length)
    BOZO_check_array_gen(i_name_byte, i_name_length)
    BOZO_CLEAN();
  BOZO_loop_array_end(i_name_byte, ARRAY_SIZE(s_decoded.i_name_byte))
  BOZO_end_array


  BOZO_END(network name);

  return i_err;
}

/* service list */
static int main_dvb_service_list_(void)
{
  BOZO_VARS(dvb_service_list);
  BOZO_START(service list);

  
  /* check i_service */
  BOZO_init_array(i_service_count);
  BOZO_begin_array(i_service)
  BOZO_loop_array_begin(i_service, i_service_count, 1)
    BOZO_DOJOB(dvb_service_list);
    BOZO_check_array_begin(i_service, i_service_count)
    BOZO_check_array_cmp(i_service, i_service_count, dvbpsi_service_list_service_s)
    BOZO_CLEAN();
  BOZO_loop_array_end(i_service, ARRAY_SIZE(s_decoded.i_service))
  BOZO_end_array


  BOZO_END(service list);

  return i_err;
}

/* stuffing */
static int main_dvb_stuffing_(void)
{
  BOZO_VARS(dvb_stuffing);
  BOZO_START(stuffing);

  
  /* check i_stuffing_byte */
  BOZO_init_array(i_stuffing_length);
  BOZO_begin_array(i_stuffing_byte)
  BOZO_loop_array_begin(i_stuffing_byte, i_stuffing_length, 0)
    BOZO_DOJOB(dvb_stuffing);
    BOZO_check_array_begin(i_stuffing_byte, i_stuffing_length)
    BOZO_check_array_gen(i_stuffing_byte, i_stuffing_length)
    BOZO_CLEAN();
  BOZO_loop_array_end(i_stuffing_byte, ARRAY_SIZE(s_decoded.i_stuffing_byte))
  BOZO_end_array


  BOZO_END(stuffing);

  return i_err;
}

/* satellite delivery system */
static int main_dvb_sat_deliv_sys_(void)
{
  BOZO_VARS(dvb_sat_deliv_sys);
  BOZO_START(satellite delivery system);

  
  /* check i_frequency */
  BOZO_init_integer(i_frequency, 0);
  BOZO_init_integer(i_orbital_position, 0);
  BOZO_init_integer(i_west_east_flag, 0);
  BOZO_init_integer(i_polarization, 0);
  BOZO_init_integer(i_roll_off, 0);
  BOZO_init_integer(i_modulation_system, 0);
  BOZO_init_integer(i_modulation_type, 0);
  BOZO_init_integer(i_symbol_rate, 0);
  BOZO_init_integer(i_fec_inner, 0);
  BOZO_begin_integer(i_frequency, 32)
    BOZO_DOJOB(dvb_sat_deliv_sys);
    BOZO_check_integer(i_frequency, 32)
    BOZO_CLEAN();
  BOZO_end_integer(i_frequency, 32)

  /* check i_orbital_position */
  BOZO_init_integer(i_frequency, 0);
  BOZO_init_integer(i_orbital_position, 0);
  BOZO_init_integer(i_west_east_flag, 0);
  BOZO_init_integer(i_polarization, 0);
  BOZO_init_integer(i_roll_off, 0);
  BOZO_init_integer(i_modulation_system, 0);
  BOZO_init_integer(i_modulation_type, 0);
  BOZO_init_integer(i_symbol_rate, 0);
  BOZO_init_integer(i_fec_inner, 0);
  BOZO_begin_integer(i_orbital_position, 16)
    BOZO_DOJOB(dvb_sat_deliv_sys);
    BOZO_check_integer(i_orbital_position, 16)
    BOZO_CLEAN();
  BOZO_end_integer(i_orbital_position, 16)

  /* check i_west_east_flag */
  BOZO_init_integer(i_frequency, 0);
  BOZO_init_integer(i_orbital_position, 0);
  BOZO_init_integer(i_west_east_flag, 0);
  BOZO_init_integer(i_polarization, 0);
  BOZO_init_integer(i_roll_off, 0);
  BOZO_init_integer(i_modulation_system, 0);
  BOZO_init_integer(i_modulation_type, 0);
  BOZO_init_integer(i_symbol_rate, 0);
  BOZO_init_integer(i_fec_inner, 0);
  BOZO_begin_integer(i_west_east_flag, 1)
    BOZO_DOJOB(dvb_sat_deliv_sys);
    BOZO_check_integer(i_west_east_flag, 1)
    BOZO_CLEAN();
  BOZO_end_integer(i_west_east_flag, 1)

  /* check i_polarization */
  BOZO_init_integer(i_frequency, 0);
  BOZO_init_integer(i_orbital_position, 0);
  BOZO_init_integer(i_west_east_flag, 0);
  BOZO_init_integer(i_polarization, 0);
  BOZO_init_integer(i_roll_off, 0);
  BOZO_init_integer(i_modulation_system, 0);
  BOZO_init_integer(i_modulation_type, 0);
  BOZO_init_integer(i_symbol_rate, 0);
  BOZO_init_integer(i_fec_inner, 0);
  BOZO_begin_integer(i_polarization, 2)
    BOZO_DOJOB(dvb_sat_deliv_sys);
    BOZO_check_integer(i_polarization, 2)
    BOZO_CLEAN();
  BOZO_end_integer(i_polarization, 2)

  /* check i_roll_off */
  BOZO_init_integer(i_frequency, 0);
  BOZO_init_integer(i_orbital_position, 0);
  BOZO_init_integer(i_west_east_flag, 0);
  BOZO_init_integer(i_polarization, 0);
  BOZO_init_integer(i_roll_off, 0);
  BOZO_init_integer(i_modulation_system, 0);
  BOZO_init_integer(i_modulation_type, 0);
  BOZO_init_integer(i_symbol_rate, 0);
  BOZO_init_integer(i_fec_inner, 0);
  BOZO_begin_integer(i_roll_off, 2)
    BOZO_DOJOB(dvb_sat_deliv_sys);
    BOZO_check_integer(i_roll_off, 2)
    BOZO_CLEAN();
  BOZO_end_integer(i_roll_off, 2)

  /* check i_modulation_system */
  BOZO_init_integer(i_frequency, 0);
  BOZO_init_integer(i_orbital_position, 0);
  BOZO_init_integer(i_west_east_flag, 0);
  BOZO_init_integer(i_polarization, 0);
  BOZO_init_integer(i_roll_off, 0);
  BOZO_init_integer(i_modulation_system, 0);
  BOZO_init_integer(i_modulation_type, 0);
  BOZO_init_integer(i_symbol_rate, 0);
  BOZO_init_integer(i_fec_inner, 0);
  BOZO_begin_integer(i_modulation_system, 1)
    BOZO_DOJOB(dvb_sat_deliv_sys);
    BOZO_check_integer(i_modulation_system, 1)
    BOZO_CLEAN();
  BOZO_end_integer(i_modulation_system, 1)

  /* check i_modulation_type */
  BOZO_init_integer(i_frequency, 0);
  BOZO_init_integer(i_orbital_position, 0);
  BOZO_init_integer(i_west_east_flag, 0);
  BOZO_init_integer(i_polarization, 0);
  BOZO_init_integer(i_roll_off, 0);
  BOZO_init_integer(i_modulation_system, 0);
  BOZO_init_integer(i_modulation_type, 0);
  BOZO_init_integer(i_symbol_rate, 0);
  BOZO_init_integer(i_fec_inner, 0);
  BOZO_begin_integer(i_modulation_type, 2)
    BOZO_DOJOB(dvb_sat_deliv_sys);
    BOZO_check_integer(i_modulation_type, 2)
    BOZO_CLEAN();
  BOZO_end_integer(i_modulation_type, 2)

  /* check i_symbol_rate */
  BOZO_init_integer(i_frequency, 0);
  BOZO_init_integer(i_orbital_position, 0);
  BOZO_init_integer(i_west_east_flag, 0);
  BOZO_init_integer(i_polarization, 0);
  BOZO_init_integer(i_roll_off, 0);
  BOZO_init_integer(i_modulation_system, 0);
  BOZO_init_integer(i_modulation_type, 0);
  BOZO_init_integer(i_symbol_rate, 0);
  BOZO_init_integer(i_fec_inner, 0);
  BOZO_begin_integer(i_symbol_rate, 28)
    BOZO_DOJOB(dvb_sat_deliv_sys);
    BOZO_check_integer(i_symbol_rate, 28)
    BOZO_CLEAN();
  BOZO_end_integer(i_symbol_rate, 28)

  /* check i_fec_inner */
  BOZO_init_integer(i_frequency, 0);
  BOZO_init_integer(i_orbital_position, 0);
  BOZO_init_integer(i_west_east_flag, 0);
  BOZO_init_integer(i_polarization, 0);
  BOZO_init_integer(i_roll_off, 0);
  BOZO_init_integer(i_modulation_system, 0);
  BOZO_init_integer(i_modulation_type, 0);
  BOZO_init_integer(i_symbol_rate, 0);
  BOZO_init_integer(i_fec_inner, 0);
  BOZO_begin_integer(i_fec_inner, 4)
    BOZO_DOJOB(dvb_sat_deliv_sys);
    BOZO_check_integer(i_fec_inner, 4)
    BOZO_CLEAN();
  BOZO_end_integer(i_fec_inner, 4)


  BOZO_END(satellite delivery system);

  return i_err;
}

/* cable delivery system */
static int main_dvb_cable_deliv_sys_(void)
{
  BOZO_VARS(dvb_cable_deliv_sys);
  BOZO_START(cable delivery system);

  
  /* check i_frequency */
  BOZO_init_integer(i_frequency, 0);
  BOZO_init_integer(i_modulation, 0);
  BOZO_init_integer(i_symbol_rate, 0);
  BOZO_init_integer(i_fec_inner, 0);
  BOZO_init_integer(i_fec_outer, 0);
  BOZO_begin_integer(i_frequency, 32)
    BOZO_DOJOB(dvb_cable_deliv_sys);
    BOZO_check_integer(i_frequency, 32)
    BOZO_CLEAN();
  BOZO_end_integer(i_frequency, 32)

  /* check i_modulation */
  BOZO_init_integer(i_frequency, 0);
  BOZO_init_integer(i_modulation, 0);
  BOZO_init_integer(i_symbol_rate, 0);
  BOZO_init_integer(i_fec_inner, 0);
  BOZO_init_integer(i_fec_outer, 0);
  BOZO_begin_integer(i_modulation, 8)
    BOZO_DOJOB(dvb_cable_deliv_sys);
    BOZO_check_integer(i_modulation, 8)
    BOZO_CLEAN();
  BOZO_end_integer(i_modulation, 8)

  /* check i_symbol_rate */
  BOZO_init_integer(i_frequency, 0);
  BOZO_init_integer(i_modulation, 0);
  BOZO_init_integer(i_symbol_rate, 0);
  BOZO_init_integer(i_fec_inner, 0);
  BOZO_init_integer(i_fec_outer, 0);
  BOZO_begin_integer(i_symbol_rate, 28)
    BOZO_DOJOB(dvb_cable_deliv_sys);
    BOZO_check_integer(i_symbol_rate, 28)
    BOZO_CLEAN();
  BOZO_end_integer(i_symbol_rate, 28)

  /* check i_fec_inner */
  BOZO_init_integer(i_frequency, 0);
  BOZO_init_integer(i_modulation, 0);
  BOZO_init_integer(i_symbol_rate, 0);
  BOZO_init_integer(i_fec_inner, 0);
  BOZO_init_integer(i_fec_outer, 0);
  BOZO_begin_integer(i_fec_inner, 4)
    BOZO_DOJOB(dvb_cable_deliv_sys);
    BOZO_check_integer(i_fec_inner, 4)
    BOZO_CLEAN();
  BOZO_end_integer(i_fec_inner, 4)

  /* check i_fec_outer */
  BOZO_init_integer(i_frequency, 0);
  BOZO_init_integer(i_modulation, 0);
  BOZO_init_integer(i_symbol_rate, 0);
  BOZO_init_integer(i_fec_inner, 0);
  BOZO_init_integer(i_fec_outer, 0);
  BOZO_begin_integer(i_fec_outer, 4)
    BOZO_DOJOB(dvb_cable_deliv_sys);
    BOZO_check_integer(i_fec_outer, 4)
    BOZO_CLEAN();
  BOZO_end_integer(i_fec_outer, 4)


  BOZO_END(cable delivery system);

  return i_err;
}

/* bouquet name */
static int main_dvb_bouquet_name_(void)
{
  BOZO_VARS(dvb_bouquet_name);
  BOZO_START(bouquet name);

  
  /* check i_char */
  BOZO_init_array(i_name_length);
  BOZO_begin_array(i_char)
  BOZO_loop_array_begin(i_char, i_name_length, 0)
    BOZO_DOJOB(dvb_bouquet_name);
    BOZO_check_array_begin(i_char, i_name_length)
    BOZO_check_array_gen(i_char, i_name_length)
    BOZO_CLEAN();
  BOZO_loop_array_end(i_char, ARRAY_SIZE(s_decoded.i_char))
  BOZO_end_array


  BOZO_END(bouquet name);

  return i_err;
}

/* service (i_service_provider_name) */
static int main_dvb_service_1(void)
{
  BOZO_VARS(dvb_service);
  BOZO_START(service (i_service_provider_name));

  
  /* check i_service_type */
  s_decoded.i_service_name_length = 0;
  BOZO_init_integer(i_service_type, 0);
  BOZO_init_array(i_service_provider_name_length);
  BOZO_begin_integer(i_service_type, 8)
    BOZO_DOJOB(dvb_service);
    BOZO_check_integer(i_service_type, 8)
    BOZO_CLEAN();
  BOZO_end_integer(i_service_type, 8)

  /* check i_service_provider_name */
  s_decoded.i_service_name_length = 0;
  BOZO_init_integer(i_service_type, 0);
  BOZO_init_array(i_service_provider_name_length);
  BOZO_begin_array(i_service_provider_name)
  BOZO_loop_array_begin(i_service_provider_name, i_service_provider_name_length, 0)
    BOZO_DOJOB(dvb_service);
    BOZO_check_array_begin(i_service_provider_name, i_service_provider_name_length)
    BOZO_check_array_gen(i_service_provider_name, i_service_provider_name_length)
    BOZO_CLEAN();
  BOZO_loop_array_end(i_service_provider_name, ARRAY_SIZE(s_decoded.i_service_provider_name))
  BOZO_end_array


  BOZO_END(service (i_service_provider_name));

  return i_err;
}

/* service (i_service_name) */
static int main_dvb_service_2(void)
{
  BOZO_VARS(dvb_service);
  BOZO_START(service (i_service_name));

  
  /* check i_service_type */
  s_decoded.i_service_provider_name_length = 0;
  BOZO_init_integer(i_service_type, 0);
  BOZO_init_array(i_service_name_length);
  BOZO_begin_integer(i_service_type, 8)
    BOZO_DOJOB(dvb_service);
    BOZO_check_integer(i_service_type, 8)
    BOZO_CLEAN();
  BOZO_end_integer(i_service_type, 8)

  /* check i_service_name */
  s_decoded.i_service_provider_name_length = 0;
  BOZO_init_integer(i_service_type, 0);
  BOZO_init_array(i_service_name_length);
  BOZO_begin_array(i_service_name)
  BOZO_loop_array_begin(i_service_name, i_service_name_length, 0)
    BOZO_DOJOB(dvb_service);
    BOZO_check_array_begin(i_service_name, i_service_name_length)
    BOZO_check_array_gen(i_service_name, i_service_name_length)
    BOZO_CLEAN();
  BOZO_loop_array_end(i_service_name, ARRAY_SIZE(s_decoded.i_service_name))
  BOZO_end_array


  BOZO_END(service (i_service_name));

  return i_err;
}

/* service (both names) */
static int main_dvb_service_3(void)
{
  BOZO_VARS(dvb_service);
  BOZO_START(service (both names));

  
  /* check i_service_type */
  s_decoded.i_service_provider_name_length = 0;
  BOZO_init_integer(i_service_type, 0);
  BOZO_init_array(i_service_name_length);
  BOZO_init_array(i_service_provider_name_length);
  BOZO_begin_integer(i_service_type, 8)
    BOZO_DOJOB(dvb_service);
    BOZO_check_integer(i_service_type, 8)
    BOZO_CLEAN();
  BOZO_end_integer(i_service_type, 8)

  /* check i_service_name */
  s_decoded.i_service_provider_name_length = 0;
  BOZO_init_integer(i_service_type, 0);
  BOZO_init_array(i_service_name_length);
  BOZO_init_array(i_service_provider_name_length);
  BOZO_begin_array(i_service_name)
  BOZO_loop_array_begin(i_service_name, i_service_name_length, 0)
    BOZO_DOJOB(dvb_service);
    BOZO_check_array_begin(i_service_name, i_service_name_length)
    BOZO_check_array_gen(i_service_name, i_service_name_length)
    BOZO_CLEAN();
  BOZO_loop_array_end(i_service_name, 126)
  BOZO_end_array

  /* check i_service_provider_name */
  s_decoded.i_service_provider_name_length = 0;
  BOZO_init_integer(i_service_type, 0);
  BOZO_init_array(i_service_name_length);
  BOZO_init_array(i_service_provider_name_length);
  BOZO_begin_array(i_service_provider_name)
  BOZO_loop_array_begin(i_service_provider_name, i_service_provider_name_length, 0)
    BOZO_DOJOB(dvb_service);
    BOZO_check_array_begin(i_service_provider_name, i_service_provider_name_length)
    BOZO_check_array_gen(i_service_provider_name, i_service_provider_name_length)
    BOZO_CLEAN();
  BOZO_loop_array_end(i_service_provider_name, 126)
  BOZO_end_array


  BOZO_END(service (both names));

  return i_err;
}

/* linkage (information service) */
static int main_dvb_linkage_0(void)
{
  BOZO_VARS(dvb_linkage);
  BOZO_START(linkage (information service));

  
  /* check i_transport_stream_id */
  s_decoded.i_linkage_type = 1;
      
  BOZO_init_integer(i_transport_stream_id, 0);
  BOZO_init_integer(i_original_network_id, 0);
  BOZO_init_integer(i_service_id, 0);
  BOZO_init_array(i_private_data_length);
  BOZO_begin_integer(i_transport_stream_id, 16)
    BOZO_DOJOB(dvb_linkage);
    BOZO_check_integer(i_transport_stream_id, 16)
    BOZO_CLEAN();
  BOZO_end_integer(i_transport_stream_id, 16)

  /* check i_original_network_id */
  s_decoded.i_linkage_type = 1;
      
  BOZO_init_integer(i_transport_stream_id, 0);
  BOZO_init_integer(i_original_network_id, 0);
  BOZO_init_integer(i_service_id, 0);
  BOZO_init_array(i_private_data_length);
  BOZO_begin_integer(i_original_network_id, 16)
    BOZO_DOJOB(dvb_linkage);
    BOZO_check_integer(i_original_network_id, 16)
    BOZO_CLEAN();
  BOZO_end_integer(i_original_network_id, 16)

  /* check i_service_id */
  s_decoded.i_linkage_type = 1;
      
  BOZO_init_integer(i_transport_stream_id, 0);
  BOZO_init_integer(i_original_network_id, 0);
  BOZO_init_integer(i_service_id, 0);
  BOZO_init_array(i_private_data_length);
  BOZO_begin_integer(i_service_id, 16)
    BOZO_DOJOB(dvb_linkage);
    BOZO_check_integer(i_service_id, 16)
    BOZO_CLEAN();
  BOZO_end_integer(i_service_id, 16)

  /* check i_private_data */
  s_decoded.i_linkage_type = 1;
      
  BOZO_init_integer(i_transport_stream_id, 0);
  BOZO_init_integer(i_original_network_id, 0);
  BOZO_init_integer(i_service_id, 0);
  BOZO_init_array(i_private_data_length);
  BOZO_begin_array(i_private_data)
  BOZO_loop_array_begin(i_private_data, i_private_data_length, 0)
    BOZO_DOJOB(dvb_linkage);
    BOZO_check_array_begin(i_private_data, i_private_data_length)
    BOZO_check_array_gen(i_private_data, i_private_data_length)
    BOZO_CLEAN();
  BOZO_loop_array_end(i_private_data, ARRAY_SIZE(s_decoded.i_private_data))
  BOZO_end_array


  BOZO_END(linkage (information service));

  return i_err;
}

/* linkage (mobile handover, no extra data) */
static int main_dvb_linkage_1(void)
{
  BOZO_VARS(dvb_linkage);
  BOZO_START(linkage (mobile handover, no extra data));

  
  /* check i_transport_stream_id */
  s_decoded.i_linkage_type = 8;
  s_decoded.i_handover_type = 0;
  s_decoded.i_origin_type = 1;
      
  BOZO_init_integer(i_transport_stream_id, 0);
  BOZO_init_integer(i_original_network_id, 0);
  BOZO_init_integer(i_service_id, 0);
  BOZO_init_array(i_private_data_length);
  BOZO_begin_integer(i_transport_stream_id, 16)
    BOZO_DOJOB(dvb_linkage);
    BOZO_check_integer(i_transport_stream_id, 16)
    BOZO_CLEAN();
  BOZO_end_integer(i_transport_stream_id, 16)

  /* check i_original_network_id */
  s_decoded.i_linkage_type = 8;
  s_decoded.i_handover_type = 0;
  s_decoded.i_origin_type = 1;
      
  BOZO_init_integer(i_transport_stream_id, 0);
  BOZO_init_integer(i_original_network_id, 0);
  BOZO_init_integer(i_service_id, 0);
  BOZO_init_array(i_private_data_length);
  BOZO_begin_integer(i_original_network_id, 16)
    BOZO_DOJOB(dvb_linkage);
    BOZO_check_integer(i_original_network_id, 16)
    BOZO_CLEAN();
  BOZO_end_integer(i_original_network_id, 16)

  /* check i_service_id */
  s_decoded.i_linkage_type = 8;
  s_decoded.i_handover_type = 0;
  s_decoded.i_origin_type = 1;
      
  BOZO_init_integer(i_transport_stream_id, 0);
  BOZO_init_integer(i_original_network_id, 0);
  BOZO_init_integer(i_service_id, 0);
  BOZO_init_array(i_private_data_length);
  BOZO_begin_integer(i_service_id, 16)
    BOZO_DOJOB(dvb_linkage);
    BOZO_check_integer(i_service_id, 16)
    BOZO_CLEAN();
  BOZO_end_integer(i_service_id, 16)

  /* check i_private_data */
  s_decoded.i_linkage_type = 8;
  s_decoded.i_handover_type = 0;
  s_decoded.i_origin_type = 1;
      
  BOZO_init_integer(i_transport_stream_id, 0);
  BOZO_init_integer(i_original_network_id, 0);
  BOZO_init_integer(i_service_id, 0);
  BOZO_init_array(i_private_data_length);
  BOZO_begin_array(i_private_data)
  BOZO_loop_array_begin(i_private_data, i_private_data_length, 0)
    BOZO_DOJOB(dvb_linkage);
    BOZO_check_array_begin(i_private_data, i_private_data_length)
    BOZO_check_array_gen(i_private_data, i_private_data_length)
    BOZO_CLEAN();
  BOZO_loop_array_end(i_private_data, 245)
  BOZO_end_array


  BOZO_END(linkage (mobile handover, no extra data));

  return i_err;
}

/* linkage (mobile handover, extra network_id) */
static int main_dvb_linkage_2(void)
{
  BOZO_VARS(dvb_linkage);
  BOZO_START(linkage (mobile handover, extra network_id));

  
  /* check i_transport_stream_id */
  s_decoded.i_linkage_type = 8;
  s_decoded.i_handover_type = 1;
  s_decoded.i_origin_type = 1;
      
  BOZO_init_integer(i_transport_stream_id, 0);
  BOZO_init_integer(i_original_network_id, 0);
  BOZO_init_integer(i_service_id, 0);
  BOZO_init_integer(i_network_id, 0);
  BOZO_init_array(i_private_data_length);
  BOZO_begin_integer(i_transport_stream_id, 16)
    BOZO_DOJOB(dvb_linkage);
    BOZO_check_integer(i_transport_stream_id, 16)
    BOZO_CLEAN();
  BOZO_end_integer(i_transport_stream_id, 16)

  /* check i_original_network_id */
  s_decoded.i_linkage_type = 8;
  s_decoded.i_handover_type = 1;
  s_decoded.i_origin_type = 1;
      
  BOZO_init_integer(i_transport_stream_id, 0);
  BOZO_init_integer(i_original_network_id, 0);
  BOZO_init_integer(i_service_id, 0);
  BOZO_init_integer(i_network_id, 0);
  BOZO_init_array(i_private_data_length);
  BOZO_begin_integer(i_original_network_id, 16)
    BOZO_DOJOB(dvb_linkage);
    BOZO_check_integer(i_original_network_id, 16)
    BOZO_CLEAN();
  BOZO_end_integer(i_original_network_id, 16)

  /* check i_service_id */
  s_decoded.i_linkage_type = 8;
  s_decoded.i_handover_type = 1;
  s_decoded.i_origin_type = 1;
      
  BOZO_init_integer(i_transport_stream_id, 0);
  BOZO_init_integer(i_original_network_id, 0);
  BOZO_init_integer(i_service_id, 0);
  BOZO_init_integer(i_network_id, 0);
  BOZO_init_array(i_private_data_length);
  BOZO_begin_integer(i_service_id, 16)
    BOZO_DOJOB(dvb_linkage);
    BOZO_check_integer(i_service_id, 16)
    BOZO_CLEAN();
  BOZO_end_integer(i_service_id, 16)

  /* check i_network_id */
  s_decoded.i_linkage_type = 8;
  s_decoded.i_handover_type = 1;
  s_decoded.i_origin_type = 1;
      
  BOZO_init_integer(i_transport_stream_id, 0);
  BOZO_init_integer(i_original_network_id, 0);
  BOZO_init_integer(i_service_id, 0);
  BOZO_init_integer(i_network_id, 0);
  BOZO_init_array(i_private_data_length);
  BOZO_begin_integer(i_network_id, 16)
    BOZO_DOJOB(dvb_linkage);
    BOZO_check_integer(i_network_id, 16)
    BOZO_CLEAN();
  BOZO_end_integer(i_network_id, 16)

  /* check i_private_data */
  s_decoded.i_linkage_type = 8;
  s_decoded.i_handover_type = 1;
  s_decoded.i_origin_type = 1;
      
  BOZO_init_integer(i_transport_stream_id, 0);
  BOZO_init_integer(i_original_network_id, 0);
  BOZO_init_integer(i_service_id, 0);
  BOZO_init_integer(i_network_id, 0);
  BOZO_init_array(i_private_data_length);
  BOZO_begin_array(i_private_data)
  BOZO_loop_array_begin(i_private_data, i_private_data_length, 0)
    BOZO_DOJOB(dvb_linkage);
    BOZO_check_array_begin(i_private_data, i_private_data_length)
    BOZO_check_array_gen(i_private_data, i_private_data_length)
    BOZO_CLEAN();
  BOZO_loop_array_end(i_private_data, 243)
  BOZO_end_array


  BOZO_END(linkage (mobile handover, extra network_id));

  return i_err;
}

/* linkage (mobile handover, extra initial_service_id) */
static int main_dvb_linkage_3(void)
{
  BOZO_VARS(dvb_linkage);
  BOZO_START(linkage (mobile handover, extra initial_service_id));

  
  /* check i_transport_stream_id */
  s_decoded.i_linkage_type = 8;
  s_decoded.i_handover_type = 0;
  s_decoded.i_origin_type = 0;
      
  BOZO_init_integer(i_transport_stream_id, 0);
  BOZO_init_integer(i_original_network_id, 0);
  BOZO_init_integer(i_service_id, 0);
  BOZO_init_integer(i_initial_service_id, 0);
  BOZO_init_array(i_private_data_length);
  BOZO_begin_integer(i_transport_stream_id, 16)
    BOZO_DOJOB(dvb_linkage);
    BOZO_check_integer(i_transport_stream_id, 16)
    BOZO_CLEAN();
  BOZO_end_integer(i_transport_stream_id, 16)

  /* check i_original_network_id */
  s_decoded.i_linkage_type = 8;
  s_decoded.i_handover_type = 0;
  s_decoded.i_origin_type = 0;
      
  BOZO_init_integer(i_transport_stream_id, 0);
  BOZO_init_integer(i_original_network_id, 0);
  BOZO_init_integer(i_service_id, 0);
  BOZO_init_integer(i_initial_service_id, 0);
  BOZO_init_array(i_private_data_length);
  BOZO_begin_integer(i_original_network_id, 16)
    BOZO_DOJOB(dvb_linkage);
    BOZO_check_integer(i_original_network_id, 16)
    BOZO_CLEAN();
  BOZO_end_integer(i_original_network_id, 16)

  /* check i_service_id */
  s_decoded.i_linkage_type = 8;
  s_decoded.i_handover_type = 0;
  s_decoded.i_origin_type = 0;
      
  BOZO_init_integer(i_transport_stream_id, 0);
  BOZO_init_integer(i_original_network_id, 0);
  BOZO_init_integer(i_service_id, 0);
  BOZO_init_integer(i_initial_service_id, 0);
  BOZO_init_array(i_private_data_length);
  BOZO_begin_integer(i_service_id, 16)
    BOZO_DOJOB(dvb_linkage);
    BOZO_check_integer(i_service_id, 16)
    BOZO_CLEAN();
  BOZO_end_integer(i_service_id, 16)

  /* check i_initial_service_id */
  s_decoded.i_linkage_type = 8;
  s_decoded.i_handover_type = 0;
  s_decoded.i_origin_type = 0;
      
  BOZO_init_integer(i_transport_stream_id, 0);
  BOZO_init_integer(i_original_network_id, 0);
  BOZO_init_integer(i_service_id, 0);
  BOZO_init_integer(i_initial_service_id, 0);
  BOZO_init_array(i_private_data_length);
  BOZO_begin_integer(i_initial_service_id, 16)
    BOZO_DOJOB(dvb_linkage);
    BOZO_check_integer(i_initial_service_id, 16)
    BOZO_CLEAN();
  BOZO_end_integer(i_initial_service_id, 16)

  /* check i_private_data */
  s_decoded.i_linkage_type = 8;
  s_decoded.i_handover_type = 0;
  s_decoded.i_origin_type = 0;
      
  BOZO_init_integer(i_transport_stream_id, 0);
  BOZO_init_integer(i_original_network_id, 0);
  BOZO_init_integer(i_service_id, 0);
  BOZO_init_integer(i_initial_service_id, 0);
  BOZO_init_array(i_private_data_length);
  BOZO_begin_array(i_private_data)
  BOZO_loop_array_begin(i_private_data, i_private_data_length, 0)
    BOZO_DOJOB(dvb_linkage);
    BOZO_check_array_begin(i_private_data, i_private_data_length)
    BOZO_check_array_gen(i_private_data, i_private_data_length)
    BOZO_CLEAN();
  BOZO_loop_array_end(i_private_data, 243)
  BOZO_end_array


  BOZO_END(linkage (mobile handover, extra initial_service_id));

  return i_err;
}

/* linkage (mobile handover, extra network_id and initial_service_id) */
static int main_dvb_linkage_4(void)
{
  BOZO_VARS(dvb_linkage);
  BOZO_START(linkage (mobile handover, extra network_id and initial_service_id));

  
  /* check i_transport_stream_id */
  s_decoded.i_linkage_type = 8;
  s_decoded.i_handover_type = 1;
  s_decoded.i_origin_type = 0;
      
  BOZO_init_integer(i_transport_stream_id, 0);
  BOZO_init_integer(i_original_network_id, 0);
  BOZO_init_integer(i_service_id, 0);
  BOZO_init_integer(i_network_id, 0);
  BOZO_init_integer(i_initial_service_id, 0);
  BOZO_init_array(i_private_data_length);
  BOZO_begin_integer(i_transport_stream_id, 16)
    BOZO_DOJOB(dvb_linkage);
    BOZO_check_integer(i_transport_stream_id, 16)
    BOZO_CLEAN();
  BOZO_end_integer(i_transport_stream_id, 16)

  /* check i_original_network_id */
  s_decoded.i_linkage_type = 8;
  s_decoded.i_handover_type = 1;
  s_decoded.i_origin_type = 0;
      
  BOZO_init_integer(i_transport_stream_id, 0);
  BOZO_init_integer(i_original_network_id, 0);
  BOZO_init_integer(i_service_id, 0);
  BOZO_init_integer(i_network_id, 0);
  BOZO_init_integer(i_initial_service_id, 0);
  BOZO_init_array(i_private_data_length);
  BOZO_begin_integer(i_original_network_id, 16)
    BOZO_DOJOB(dvb_linkage);
    BOZO_check_integer(i_original_network_id, 16)
    BOZO_CLEAN();
  BOZO_end_integer(i_original_network_id, 16)

  /* check i_service_id */
  s_decoded.i_linkage_type = 8;
  s_decoded.i_handover_type = 1;
  s_decoded.i_origin_type = 0;
      
  BOZO_init_integer(i_transport_stream_id, 0);
  BOZO_init_integer(i_original_network_id, 0);
  BOZO_init_integer(i_service_id, 0);
  BOZO_init_integer(i_network_id, 0);
  BOZO_init_integer(i_initial_service_id, 0);
  BOZO_init_array(i_private_data_length);
  BOZO_begin_integer(i_service_id, 16)
    BOZO_DOJOB(dvb_linkage);
    BOZO_check_integer(i_service_id, 16)
    BOZO_CLEAN();
  BOZO_end_integer(i_service_id, 16)

  /* check i_network_id */
  s_decoded.i_linkage_type = 8;
  s_decoded.i_handover_type = 1;
  s_decoded.i_origin_type = 0;
      
  BOZO_init_integer(i_transport_stream_id, 0);
  BOZO_init_integer(i_original_network_id, 0);
  BOZO_init_integer(i_service_id, 0);
  BOZO_init_integer(i_network_id, 0);
  BOZO_init_integer(i_initial_service_id, 0);
  BOZO_init_array(i_private_data_length);
  BOZO_begin_integer(i_network_id, 16)
    BOZO_DOJOB(dvb_linkage);
    BOZO_check_integer(i_network_id, 16)
    BOZO_CLEAN();
  BOZO_end_integer(i_network_id, 16)

  /* check i_initial_service_id */
  s_decoded.i_linkage_type = 8;
  s_decoded.i_handover_type = 1;
  s_decoded.i_origin_type = 0;
      
  BOZO_init_integer(i_transport_stream_id, 0);
  BOZO_init_integer(i_original_network_id, 0);
  BOZO_init_integer(i_service_id, 0);
  BOZO_init_integer(i_network_id, 0);
  BOZO_init_integer(i_initial_service_id, 0);
  BOZO_init_array(i_private_data_length);
  BOZO_begin_integer(i_initial_service_id, 16)
    BOZO_DOJOB(dvb_linkage);
    BOZO_check_integer(i_initial_service_id, 16)
    BOZO_CLEAN();
  BOZO_end_integer(i_initial_service_id, 16)

  /* check i_private_data */
  s_decoded.i_linkage_type = 8;
  s_decoded.i_handover_type = 1;
  s_decoded.i_origin_type = 0;
      
  BOZO_init_integer(i_transport_stream_id, 0);
  BOZO_init_integer(i_original_network_id, 0);
  BOZO_init_integer(i_service_id, 0);
  BOZO_init_integer(i_network_id, 0);
  BOZO_init_integer(i_initial_service_id, 0);
  BOZO_init_array(i_private_data_length);
  BOZO_begin_array(i_private_data)
  BOZO_loop_array_begin(i_private_data, i_private_data_length, 0)
    BOZO_DOJOB(dvb_linkage);
    BOZO_check_array_begin(i_private_data, i_private_data_length)
    BOZO_check_array_gen(i_private_data, i_private_data_length)
    BOZO_CLEAN();
  BOZO_loop_array_end(i_private_data, 241)
  BOZO_end_array


  BOZO_END(linkage (mobile handover, extra network_id and initial_service_id));

  return i_err;
}

/* linkage (event linkage) */
static int main_dvb_linkage_5(void)
{
  BOZO_VARS(dvb_linkage);
  BOZO_START(linkage (event linkage));

  
  /* check i_transport_stream_id */
  s_decoded.i_linkage_type = 13;
      
  BOZO_init_integer(i_transport_stream_id, 0);
  BOZO_init_integer(i_original_network_id, 0);
  BOZO_init_integer(i_service_id, 0);
  BOZO_init_integer(i_target_event_id, 0);
  BOZO_init_boolean(b_target_listed, 0);
  BOZO_init_boolean(b_event_simulcast, 0);
  BOZO_init_array(i_private_data_length);
  BOZO_begin_integer(i_transport_stream_id, 16)
    BOZO_DOJOB(dvb_linkage);
    BOZO_check_integer(i_transport_stream_id, 16)
    BOZO_CLEAN();
  BOZO_end_integer(i_transport_stream_id, 16)

  /* check i_original_network_id */
  s_decoded.i_linkage_type = 13;
      
  BOZO_init_integer(i_transport_stream_id, 0);
  BOZO_init_integer(i_original_network_id, 0);
  BOZO_init_integer(i_service_id, 0);
  BOZO_init_integer(i_target_event_id, 0);
  BOZO_init_boolean(b_target_listed, 0);
  BOZO_init_boolean(b_event_simulcast, 0);
  BOZO_init_array(i_private_data_length);
  BOZO_begin_integer(i_original_network_id, 16)
    BOZO_DOJOB(dvb_linkage);
    BOZO_check_integer(i_original_network_id, 16)
    BOZO_CLEAN();
  BOZO_end_integer(i_original_network_id, 16)

  /* check i_service_id */
  s_decoded.i_linkage_type = 13;
      
  BOZO_init_integer(i_transport_stream_id, 0);
  BOZO_init_integer(i_original_network_id, 0);
  BOZO_init_integer(i_service_id, 0);
  BOZO_init_integer(i_target_event_id, 0);
  BOZO_init_boolean(b_target_listed, 0);
  BOZO_init_boolean(b_event_simulcast, 0);
  BOZO_init_array(i_private_data_length);
  BOZO_begin_integer(i_service_id, 16)
    BOZO_DOJOB(dvb_linkage);
    BOZO_check_integer(i_service_id, 16)
    BOZO_CLEAN();
  BOZO_end_integer(i_service_id, 16)

  /* check i_target_event_id */
  s_decoded.i_linkage_type = 13;
      
  BOZO_init_integer(i_transport_stream_id, 0);
  BOZO_init_integer(i_original_network_id, 0);
  BOZO_init_integer(i_service_id, 0);
  BOZO_init_integer(i_target_event_id, 0);
  BOZO_init_boolean(b_target_listed, 0);
  BOZO_init_boolean(b_event_simulcast, 0);
  BOZO_init_array(i_private_data_length);
  BOZO_begin_integer(i_target_event_id, 16)
    BOZO_DOJOB(dvb_linkage);
    BOZO_check_integer(i_target_event_id, 16)
    BOZO_CLEAN();
  BOZO_end_integer(i_target_event_id, 16)

  /* check b_target_listed */
  s_decoded.i_linkage_type = 13;
      
  BOZO_init_integer(i_transport_stream_id, 0);
  BOZO_init_integer(i_original_network_id, 0);
  BOZO_init_integer(i_service_id, 0);
  BOZO_init_integer(i_target_event_id, 0);
  BOZO_init_boolean(b_target_listed, 0);
  BOZO_init_boolean(b_event_simulcast, 0);
  BOZO_init_array(i_private_data_length);
  BOZO_begin_boolean(b_target_listed)
    BOZO_DOJOB(dvb_linkage);
    BOZO_check_boolean(b_target_listed)
    BOZO_CLEAN();
  BOZO_end_boolean(b_target_listed)

  /* check b_event_simulcast */
  s_decoded.i_linkage_type = 13;
      
  BOZO_init_integer(i_transport_stream_id, 0);
  BOZO_init_integer(i_original_network_id, 0);
  BOZO_init_integer(i_service_id, 0);
  BOZO_init_integer(i_target_event_id, 0);
  BOZO_init_boolean(b_target_listed, 0);
  BOZO_init_boolean(b_event_simulcast, 0);
  BOZO_init_array(i_private_data_length);
  BOZO_begin_boolean(b_event_simulcast)
    BOZO_DOJOB(dvb_linkage);
    BOZO_check_boolean(b_event_simulcast)
    BOZO_CLEAN();
  BOZO_end_boolean(b_event_simulcast)

  /* check i_private_data */
  s_decoded.i_linkage_type = 13;
      
  BOZO_init_integer(i_transport_stream_id, 0);
  BOZO_init_integer(i_original_network_id, 0);
  BOZO_init_integer(i_service_id, 0);
  BOZO_init_integer(i_target_event_id, 0);
  BOZO_init_boolean(b_target_listed, 0);
  BOZO_init_boolean(b_event_simulcast, 0);
  BOZO_init_array(i_private_data_length);
  BOZO_begin_array(i_private_data)
  BOZO_loop_array_begin(i_private_data, i_private_data_length, 0)
    BOZO_DOJOB(dvb_linkage);
    BOZO_check_array_begin(i_private_data, i_private_data_length)
    BOZO_check_array_gen(i_private_data, i_private_data_length)
    BOZO_CLEAN();
  BOZO_loop_array_end(i_private_data, 242)
  BOZO_end_array


  BOZO_END(linkage (event linkage));

  return i_err;
}

/* Near Video On Demand reference */
static int main_dvb_nvod_ref_(void)
{
  BOZO_VARS(dvb_nvod_ref);
  BOZO_START(Near Video On Demand reference);

  
  /* check p_nvod_refs */
  BOZO_init_array(i_references);
  BOZO_begin_array(p_nvod_refs)
  BOZO_loop_array_begin(p_nvod_refs, i_references, 1)
    BOZO_DOJOB(dvb_nvod_ref);
    BOZO_check_array_begin(p_nvod_refs, i_references)
    BOZO_check_array_cmp(p_nvod_refs, i_references, dvbpsi_nvod_ref_t)
    BOZO_CLEAN();
  BOZO_loop_array_end(p_nvod_refs, ARRAY_SIZE(s_decoded.p_nvod_refs))
  BOZO_end_array


  BOZO_END(Near Video On Demand reference);

  return i_err;
}

/* time shifted service */
static int main_dvb_tshifted_service_(void)
{
  BOZO_VARS(dvb_tshifted_service);
  BOZO_START(time shifted service);

  
  /* check i_ref_service_id */
  BOZO_init_integer(i_ref_service_id, 0);
  BOZO_begin_integer(i_ref_service_id, 16)
    BOZO_DOJOB(dvb_tshifted_service);
    BOZO_check_integer(i_ref_service_id, 16)
    BOZO_CLEAN();
  BOZO_end_integer(i_ref_service_id, 16)


  BOZO_END(time shifted service);

  return i_err;
}

/* short event (event_name) */
static int main_dvb_short_event_0(void)
{
  BOZO_VARS(dvb_short_event);
  BOZO_START(short event (event_name));

  
  /* check i_iso_639_code */
  s_decoded.i_text_length = 0;
      
  BOZO_fill_array(s_decoded.i_iso_639_code, sizeof(s_decoded.i_iso_639_code));
  BOZO_init_array(i_event_name_length);
  i_loop_count = 0;
  BOZO_begin_array(i_iso_639_code)
  BOZO_DOJOB(dvb_short_event);
  BOZO_check_carray(i_iso_639_code)
  BOZO_end_array

  /* check i_event_name */
  s_decoded.i_text_length = 0;
      
  BOZO_fill_array(s_decoded.i_iso_639_code, sizeof(s_decoded.i_iso_639_code));
  BOZO_init_array(i_event_name_length);
  BOZO_begin_array(i_event_name)
  BOZO_loop_array_begin(i_event_name, i_event_name_length, 0)
    BOZO_DOJOB(dvb_short_event);
    BOZO_check_array_begin(i_event_name, i_event_name_length)
    BOZO_check_array_gen(i_event_name, i_event_name_length)
    BOZO_CLEAN();
  BOZO_loop_array_end(i_event_name, 248)
  BOZO_end_array


  BOZO_END(short event (event_name));

  return i_err;
}

/* short event (i_text) */
static int main_dvb_short_event_1(void)
{
  BOZO_VARS(dvb_short_event);
  BOZO_START(short event (i_text));

  
  /* check i_iso_639_code */
  s_decoded.i_event_name_length = 0;
      
  BOZO_fill_array(s_decoded.i_iso_639_code, sizeof(s_decoded.i_iso_639_code));
  BOZO_init_array(i_text_length);
  i_loop_count = 0;
  BOZO_begin_array(i_iso_639_code)
  BOZO_DOJOB(dvb_short_event);
  BOZO_check_carray(i_iso_639_code)
  BOZO_end_array

  /* check i_text */
  s_decoded.i_event_name_length = 0;
      
  BOZO_fill_array(s_decoded.i_iso_639_code, sizeof(s_decoded.i_iso_639_code));
  BOZO_init_array(i_text_length);
  BOZO_begin_array(i_text)
  BOZO_loop_array_begin(i_text, i_text_length, 0)
    BOZO_DOJOB(dvb_short_event);
    BOZO_check_array_begin(i_text, i_text_length)
    BOZO_check_array_gen(i_text, i_text_length)
    BOZO_CLEAN();
  BOZO_loop_array_end(i_text, 248)
  BOZO_end_array


  BOZO_END(short event (i_text));

  return i_err;
}

/* short event (both) */
static int main_dvb_short_event_2(void)
{
  BOZO_VARS(dvb_short_event);
  BOZO_START(short event (both));

  
  /* check i_iso_639_code */
  BOZO_fill_array(s_decoded.i_iso_639_code, sizeof(s_decoded.i_iso_639_code));
  BOZO_init_array(i_text_length);
  BOZO_init_array(i_event_name_length);
  i_loop_count = 0;
  BOZO_begin_array(i_iso_639_code)
  BOZO_DOJOB(dvb_short_event);
  BOZO_check_carray(i_iso_639_code)
  BOZO_end_array

  /* check i_text */
  BOZO_fill_array(s_decoded.i_iso_639_code, sizeof(s_decoded.i_iso_639_code));
  BOZO_init_array(i_text_length);
  BOZO_init_array(i_event_name_length);
  BOZO_begin_array(i_text)
  BOZO_loop_array_begin(i_text, i_text_length, 0)
    BOZO_DOJOB(dvb_short_event);
    BOZO_check_array_begin(i_text, i_text_length)
    BOZO_check_array_gen(i_text, i_text_length)
    BOZO_CLEAN();
  BOZO_loop_array_end(i_text, 124)
  BOZO_end_array

  /* check i_event_name */
  BOZO_fill_array(s_decoded.i_iso_639_code, sizeof(s_decoded.i_iso_639_code));
  BOZO_init_array(i_text_length);
  BOZO_init_array(i_event_name_length);
  BOZO_begin_array(i_event_name)
  BOZO_loop_array_begin(i_event_name, i_event_name_length, 0)
    BOZO_DOJOB(dvb_short_event);
    BOZO_check_array_begin(i_event_name, i_event_name_length)
    BOZO_check_array_gen(i_event_name, i_event_name_length)
    BOZO_CLEAN();
  BOZO_loop_array_end(i_event_name, 124)
  BOZO_end_array


  BOZO_END(short event (both));

  return i_err;
}

/* time shifted event */
static int main_dvb_tshifted_ev_(void)
{
  BOZO_VARS(dvb_tshifted_ev);
  BOZO_START(time shifted event);

  
  /* check i_ref_service_id */
  BOZO_init_integer(i_ref_service_id, 0);
  BOZO_init_integer(i_ref_event_id, 0);
  BOZO_begin_integer(i_ref_service_id, 16)
    BOZO_DOJOB(dvb_tshifted_ev);
    BOZO_check_integer(i_ref_service_id, 16)
    BOZO_CLEAN();
  BOZO_end_integer(i_ref_service_id, 16)

  /* check i_ref_event_id */
  BOZO_init_integer(i_ref_service_id, 0);
  BOZO_init_integer(i_ref_event_id, 0);
  BOZO_begin_integer(i_ref_event_id, 16)
    BOZO_DOJOB(dvb_tshifted_ev);
    BOZO_check_integer(i_ref_event_id, 16)
    BOZO_CLEAN();
  BOZO_end_integer(i_ref_event_id, 16)


  BOZO_END(time shifted event);

  return i_err;
}

/* stream identifier */
static int main_dvb_stream_identifier_(void)
{
  BOZO_VARS(dvb_stream_identifier);
  BOZO_START(stream identifier);

  
  /* check i_component_tag */
  BOZO_init_integer(i_component_tag, 0);
  BOZO_begin_integer(i_component_tag, 8)
    BOZO_DOJOB(dvb_stream_identifier);
    BOZO_check_integer(i_component_tag, 8)
    BOZO_CLEAN();
  BOZO_end_integer(i_component_tag, 8)


  BOZO_END(stream identifier);

  return i_err;
}

/* CA identifier */
static int main_dvb_ca_identifier_(void)
{
  BOZO_VARS(dvb_ca_identifier);
  BOZO_START(CA identifier);

  
  /* check p_system */
  BOZO_init_array(i_number);
  BOZO_begin_array(p_system)
  BOZO_loop_array_begin(p_system, i_number, 1)
    BOZO_DOJOB(dvb_ca_identifier);
    BOZO_check_array_begin(p_system, i_number)
    BOZO_check_array_cmp(p_system, i_number, dvbpsi_ca_system_t)
    BOZO_CLEAN();
  BOZO_loop_array_end(p_system, ARRAY_SIZE(s_decoded.p_system))
  BOZO_end_array


  BOZO_END(CA identifier);

  return i_err;
}

/* content */
static int main_dvb_content_(void)
{
  BOZO_VARS(dvb_content);
  BOZO_START(content);

  
  /* check p_content */
  BOZO_init_array(i_contents_number);
  BOZO_begin_array(p_content)
  BOZO_loop_array_begin(p_content, i_contents_number, 1)
    BOZO_DOJOB(dvb_content);
    BOZO_check_array_begin(p_content, i_contents_number)
    BOZO_check_array_cmp(p_content, i_contents_number, dvbpsi_content_t)
    BOZO_CLEAN();
  BOZO_loop_array_end(p_content, ARRAY_SIZE(s_decoded.p_content))
  BOZO_end_array


  BOZO_END(content);

  return i_err;
}

/* parental rating */
static int main_dvb_parental_rating_(void)
{
  BOZO_VARS(dvb_parental_rating);
  BOZO_START(parental rating);

  
  /* check p_parental_rating */
  BOZO_init_array(i_ratings_number);
  BOZO_begin_array(p_parental_rating)
  BOZO_loop_array_begin(p_parental_rating, i_ratings_number, 1)
    BOZO_DOJOB(dvb_parental_rating);
    BOZO_check_array_begin(p_parental_rating, i_ratings_number)
    BOZO_check_array_cmp(p_parental_rating, i_ratings_number, dvbpsi_parental_rating_t)
    BOZO_CLEAN();
  BOZO_loop_array_end(p_parental_rating, ARRAY_SIZE(s_decoded.p_parental_rating))
  BOZO_end_array


  BOZO_END(parental rating);

  return i_err;
}

/* teletext */
static int main_dvb_teletext_(void)
{
  BOZO_VARS(dvb_teletext);
  BOZO_START(teletext);

  
  /* check p_pages */
  BOZO_init_array(i_pages_number);
  BOZO_begin_array(p_pages)
  BOZO_loop_array_begin(p_pages, i_pages_number, 1)
    BOZO_DOJOB(dvb_teletext);
    BOZO_check_array_begin(p_pages, i_pages_number)
    BOZO_check_array_cmp(p_pages, i_pages_number, dvbpsi_teletextpage_t)
    BOZO_CLEAN();
  BOZO_loop_array_end(p_pages, ARRAY_SIZE(s_decoded.p_pages))
  BOZO_end_array


  BOZO_END(teletext);

  return i_err;
}

/* local time offset */
static int main_dvb_local_time_offset_(void)
{
  BOZO_VARS(dvb_local_time_offset);
  BOZO_START(local time offset);

  
  /* check p_local_time_offset */
  BOZO_init_array(i_local_time_offsets_number);
  BOZO_begin_array(p_local_time_offset)
  BOZO_loop_array_begin(p_local_time_offset, i_local_time_offsets_number, 1)
    BOZO_DOJOB(dvb_local_time_offset);
    BOZO_check_array_begin(p_local_time_offset, i_local_time_offsets_number)
    BOZO_check_array_cmp(p_local_time_offset, i_local_time_offsets_number, dvbpsi_local_time_offset_t)
    BOZO_CLEAN();
  BOZO_loop_array_end(p_local_time_offset, ARRAY_SIZE(s_decoded.p_local_time_offset))
  BOZO_end_array


  BOZO_END(local time offset);

  return i_err;
}

/* subtitling */
static int main_dvb_subtitling_(void)
{
  BOZO_VARS(dvb_subtitling);
  BOZO_START(subtitling);

  
  /* check p_subtitle */
  BOZO_init_array(i_subtitles_number);
  BOZO_begin_array(p_subtitle)
  BOZO_loop_array_begin(p_subtitle, i_subtitles_number, 1)
    BOZO_DOJOB(dvb_subtitling);
    BOZO_check_array_begin(p_subtitle, i_subtitles_number)
    BOZO_check_array_cmp(p_subtitle, i_subtitles_number, dvbpsi_subtitle_t)
    BOZO_CLEAN();
  BOZO_loop_array_end(p_subtitle, ARRAY_SIZE(s_decoded.p_subtitle))
  BOZO_end_array


  BOZO_END(subtitling);

  return i_err;
}

/* terrestial delivery system */
static int main_dvb_terr_deliv_sys_(void)
{
  BOZO_VARS(dvb_terr_deliv_sys);
  BOZO_START(terrestial delivery system);

  
  /* check i_centre_frequency */
  BOZO_init_integer(i_centre_frequency, 0);
  BOZO_init_integer(i_bandwidth, 0);
  BOZO_init_integer(i_priority, 0);
  BOZO_init_integer(i_time_slice_indicator, 0);
  BOZO_init_integer(i_mpe_fec_indicator, 0);
  BOZO_init_integer(i_constellation, 0);
  BOZO_init_integer(i_hierarchy_information, 0);
  BOZO_init_integer(i_code_rate_hp_stream, 0);
  BOZO_init_integer(i_code_rate_lp_stream, 0);
  BOZO_init_integer(i_guard_interval, 0);
  BOZO_init_integer(i_transmission_mode, 0);
  BOZO_init_integer(i_other_frequency_flag, 0);
  BOZO_begin_integer(i_centre_frequency, 32)
    BOZO_DOJOB(dvb_terr_deliv_sys);
    BOZO_check_integer(i_centre_frequency, 32)
    BOZO_CLEAN();
  BOZO_end_integer(i_centre_frequency, 32)

  /* check i_bandwidth */
  BOZO_init_integer(i_centre_frequency, 0);
  BOZO_init_integer(i_bandwidth, 0);
  BOZO_init_integer(i_priority, 0);
  BOZO_init_integer(i_time_slice_indicator, 0);
  BOZO_init_integer(i_mpe_fec_indicator, 0);
  BOZO_init_integer(i_constellation, 0);
  BOZO_init_integer(i_hierarchy_information, 0);
  BOZO_init_integer(i_code_rate_hp_stream, 0);
  BOZO_init_integer(i_code_rate_lp_stream, 0);
  BOZO_init_integer(i_guard_interval, 0);
  BOZO_init_integer(i_transmission_mode, 0);
  BOZO_init_integer(i_other_frequency_flag, 0);
  BOZO_begin_integer(i_bandwidth, 3)
    BOZO_DOJOB(dvb_terr_deliv_sys);
    BOZO_check_integer(i_bandwidth, 3)
    BOZO_CLEAN();
  BOZO_end_integer(i_bandwidth, 3)

  /* check i_priority */
  BOZO_init_integer(i_centre_frequency, 0);
  BOZO_init_integer(i_bandwidth, 0);
  BOZO_init_integer(i_priority, 0);
  BOZO_init_integer(i_time_slice_indicator, 0);
  BOZO_init_integer(i_mpe_fec_indicator, 0);
  BOZO_init_integer(i_constellation, 0);
  BOZO_init_integer(i_hierarchy_information, 0);
  BOZO_init_integer(i_code_rate_hp_stream, 0);
  BOZO_init_integer(i_code_rate_lp_stream, 0);
  BOZO_init_integer(i_guard_interval, 0);
  BOZO_init_integer(i_transmission_mode, 0);
  BOZO_init_integer(i_other_frequency_flag, 0);
  BOZO_begin_integer(i_priority, 1)
    BOZO_DOJOB(dvb_terr_deliv_sys);
    BOZO_check_integer(i_priority, 1)
    BOZO_CLEAN();
  BOZO_end_integer(i_priority, 1)

  /* check i_time_slice_indicator */
  BOZO_init_integer(i_centre_frequency, 0);
  BOZO_init_integer(i_bandwidth, 0);
  BOZO_init_integer(i_priority, 0);
  BOZO_init_integer(i_time_slice_indicator, 0);
  BOZO_init_integer(i_mpe_fec_indicator, 0);
  BOZO_init_integer(i_constellation, 0);
  BOZO_init_integer(i_hierarchy_information, 0);
  BOZO_init_integer(i_code_rate_hp_stream, 0);
  BOZO_init_integer(i_code_rate_lp_stream, 0);
  BOZO_init_integer(i_guard_interval, 0);
  BOZO_init_integer(i_transmission_mode, 0);
  BOZO_init_integer(i_other_frequency_flag, 0);
  BOZO_begin_integer(i_time_slice_indicator, 1)
    BOZO_DOJOB(dvb_terr_deliv_sys);
    BOZO_check_integer(i_time_slice_indicator, 1)
    BOZO_CLEAN();
  BOZO_end_integer(i_time_slice_indicator, 1)

  /* check i_mpe_fec_indicator */
  BOZO_init_integer(i_centre_frequency, 0);
  BOZO_init_integer(i_bandwidth, 0);
  BOZO_init_integer(i_priority, 0);
  BOZO_init_integer(i_time_slice_indicator, 0);
  BOZO_init_integer(i_mpe_fec_indicator, 0);
  BOZO_init_integer(i_constellation, 0);
  BOZO_init_integer(i_hierarchy_information, 0);
  BOZO_init_integer(i_code_rate_hp_stream, 0);
  BOZO_init_integer(i_code_rate_lp_stream, 0);
  BOZO_init_integer(i_guard_interval, 0);
  BOZO_init_integer(i_transmission_mode, 0);
  BOZO_init_integer(i_other_frequency_flag, 0);
  BOZO_begin_integer(i_mpe_fec_indicator, 1)
    BOZO_DOJOB(dvb_terr_deliv_sys);
    BOZO_check_integer(i_mpe_fec_indicator, 1)
    BOZO_CLEAN();
  BOZO_end_integer(i_mpe_fec_indicator, 1)

  /* check i_constellation */
  BOZO_init_integer(i_centre_frequency, 0);
  BOZO_init_integer(i_bandwidth, 0);
  BOZO_init_integer(i_priority, 0);
  BOZO_init_integer(i_time_slice_indicator, 0);
  BOZO_init_integer(i_mpe_fec_indicator, 0);
  BOZO_init_integer(i_constellation, 0);
  BOZO_init_integer(i_hierarchy_information, 0);
  BOZO_init_integer(i_code_rate_hp_stream, 0);
  BOZO_init_integer(i_code_rate_lp_stream, 0);
  BOZO_init_integer(i_guard_interval, 0);
  BOZO_init_integer(i_transmission_mode, 0);
  BOZO_init_integer(i_other_frequency_flag, 0);
  BOZO_begin_integer(i_constellation, 2)
    BOZO_DOJOB(dvb_terr_deliv_sys);
    BOZO_check_integer(i_constellation, 2)
    BOZO_CLEAN();
  BOZO_end_integer(i_constellation, 2)

  /* check i_hierarchy_information */
  BOZO_init_integer(i_centre_frequency, 0);
  BOZO_init_integer(i_bandwidth, 0);
  BOZO_init_integer(i_priority, 0);
  BOZO_init_integer(i_time_slice_indicator, 0);
  BOZO_init_integer(i_mpe_fec_indicator, 0);
  BOZO_init_integer(i_constellation, 0);
  BOZO_init_integer(i_hierarchy_information, 0);
  BOZO_init_integer(i_code_rate_hp_stream, 0);
  BOZO_init_integer(i_code_rate_lp_stream, 0);
  BOZO_init_integer(i_guard_interval, 0);
  BOZO_init_integer(i_transmission_mode, 0);
  BOZO_init_integer(i_other_frequency_flag, 0);
  BOZO_begin_integer(i_hierarchy_information, 3)
    BOZO_DOJOB(dvb_terr_deliv_sys);
    BOZO_check_integer(i_hierarchy_information, 3)
    BOZO_CLEAN();
  BOZO_end_integer(i_hierarchy_information, 3)

  /* check i_code_rate_hp_stream */
  BOZO_init_integer(i_centre_frequency, 0);
  BOZO_init_integer(i_bandwidth, 0);
  BOZO_init_integer(i_priority, 0);
  BOZO_init_integer(i_time_slice_indicator, 0);
  BOZO_init_integer(i_mpe_fec_indicator, 0);
  BOZO_init_integer(i_constellation, 0);
  BOZO_init_integer(i_hierarchy_information, 0);
  BOZO_init_integer(i_code_rate_hp_stream, 0);
  BOZO_init_integer(i_code_rate_lp_stream, 0);
  BOZO_init_integer(i_guard_interval, 0);
  BOZO_init_integer(i_transmission_mode, 0);
  BOZO_init_integer(i_other_frequency_flag, 0);
  BOZO_begin_integer(i_code_rate_hp_stream, 3)
    BOZO_DOJOB(dvb_terr_deliv_sys);
    BOZO_check_integer(i_code_rate_hp_stream, 3)
    BOZO_CLEAN();
  BOZO_end_integer(i_code_rate_hp_stream, 3)

  /* check i_code_rate_lp_stream */
  BOZO_init_integer(i_centre_frequency, 0);
  BOZO_init_integer(i_bandwidth, 0);
  BOZO_init_integer(i_priority, 0);
  BOZO_init_integer(i_time_slice_indicator, 0);
  BOZO_init_integer(i_mpe_fec_indicator, 0);
  BOZO_init_integer(i_constellation, 0);
  BOZO_init_integer(i_hierarchy_information, 0);
  BOZO_init_integer(i_code_rate_hp_stream, 0);
  BOZO_init_integer(i_code_rate_lp_stream, 0);
  BOZO_init_integer(i_guard_interval, 0);
  BOZO_init_integer(i_transmission_mode, 0);
  BOZO_init_integer(i_other_frequency_flag, 0);
  BOZO_begin_integer(i_code_rate_lp_stream, 3)
    BOZO_DOJOB(dvb_terr_deliv_sys);
    BOZO_check_integer(i_code_rate_lp_stream, 3)
    BOZO_CLEAN();
  BOZO_end_integer(i_code_rate_lp_stream, 3)

  /* check i_guard_interval */
  BOZO_init_integer(i_centre_frequency, 0);
  BOZO_init_integer(i_bandwidth, 0);
  BOZO_init_integer(i_priority, 0);
  BOZO_init_integer(i_time_slice_indicator, 0);
  BOZO_init_integer(i_mpe_fec_indicator, 0);
  BOZO_init_integer(i_constellation, 0);
  BOZO_init_integer(i_hierarchy_information, 0);
  BOZO_init_integer(i_code_rate_hp_stream, 0);
  BOZO_init_integer(i_code_rate_lp_stream, 0);
  BOZO_init_integer(i_guard_interval, 0);
  BOZO_init_integer(i_transmission_mode, 0);
  BOZO_init_integer(i_other_frequency_flag, 0);
  BOZO_begin_integer(i_guard_interval, 2)
    BOZO_DOJOB(dvb_terr_deliv_sys);
    BOZO_check_integer(i_guard_interval, 2)
    BOZO_CLEAN();
  BOZO_end_integer(i_guard_interval, 2)

  /* check i_transmission_mode */
  BOZO_init_integer(i_centre_frequency, 0);
  BOZO_init_integer(i_bandwidth, 0);
  BOZO_init_integer(i_priority, 0);
  BOZO_init_integer(i_time_slice_indicator, 0);
  BOZO_init_integer(i_mpe_fec_indicator, 0);
  BOZO_init_integer(i_constellation, 0);
  BOZO_init_integer(i_hierarchy_information, 0);
  BOZO_init_integer(i_code_rate_hp_stream, 0);
  BOZO_init_integer(i_code_rate_lp_stream, 0);
  BOZO_init_integer(i_guard_interval, 0);
  BOZO_init_integer(i_transmission_mode, 0);
  BOZO_init_integer(i_other_frequency_flag, 0);
  BOZO_begin_integer(i_transmission_mode, 2)
    BOZO_DOJOB(dvb_terr_deliv_sys);
    BOZO_check_integer(i_transmission_mode, 2)
    BOZO_CLEAN();
  BOZO_end_integer(i_transmission_mode, 2)

  /* check i_other_frequency_flag */
  BOZO_init_integer(i_centre_frequency, 0);
  BOZO_init_integer(i_bandwidth, 0);
  BOZO_init_integer(i_priority, 0);
  BOZO_init_integer(i_time_slice_indicator, 0);
  BOZO_init_integer(i_mpe_fec_indicator, 0);
  BOZO_init_integer(i_constellation, 0);
  BOZO_init_integer(i_hierarchy_information, 0);
  BOZO_init_integer(i_code_rate_hp_stream, 0);
  BOZO_init_integer(i_code_rate_lp_stream, 0);
  BOZO_init_integer(i_guard_interval, 0);
  BOZO_init_integer(i_transmission_mode, 0);
  BOZO_init_integer(i_other_frequency_flag, 0);
  BOZO_begin_integer(i_other_frequency_flag, 1)
    BOZO_DOJOB(dvb_terr_deliv_sys);
    BOZO_check_integer(i_other_frequency_flag, 1)
    BOZO_CLEAN();
  BOZO_end_integer(i_other_frequency_flag, 1)


  BOZO_END(terrestial delivery system);

  return i_err;
}


/* main function */
int main(void)
{
  int i_err = 0;
  srand(time(NULL));
  
  i_err |= main_mpeg_vstream_1();
  i_err |= main_mpeg_vstream_2();
  i_err |= main_mpeg_astream_();
  i_err |= main_mpeg_hierarchy_();
  i_err |= main_mpeg_registration_();
  i_err |= main_mpeg_ds_alignment_();
  i_err |= main_mpeg_target_bg_grid_();
  i_err |= main_mpeg_vwindow_();
  i_err |= main_mpeg_ca_();
  i_err |= main_mpeg_iso639_();
  i_err |= main_mpeg_system_clock_();
  i_err |= main_mpeg_mx_buff_utilization_();
  i_err |= main_mpeg_copyright_();
  i_err |= main_mpeg_max_bitrate_();
  i_err |= main_mpeg_private_data_();
  i_err |= main_mpeg_smoothing_buffer_();
  i_err |= main_mpeg_std_();
  i_err |= main_mpeg_ibp_();
  i_err |= main_mpeg_mpeg4_video_();
  i_err |= main_mpeg_mpeg4_audio_();
  i_err |= main_dvb_network_name_();
  i_err |= main_dvb_service_list_();
  i_err |= main_dvb_stuffing_();
  i_err |= main_dvb_sat_deliv_sys_();
  i_err |= main_dvb_cable_deliv_sys_();
  i_err |= main_dvb_bouquet_name_();
  i_err |= main_dvb_service_1();
  i_err |= main_dvb_service_2();
  i_err |= main_dvb_service_3();
  i_err |= main_dvb_linkage_0();
  i_err |= main_dvb_linkage_1();
  i_err |= main_dvb_linkage_2();
  i_err |= main_dvb_linkage_3();
  i_err |= main_dvb_linkage_4();
  i_err |= main_dvb_linkage_5();
  i_err |= main_dvb_nvod_ref_();
  i_err |= main_dvb_tshifted_service_();
  i_err |= main_dvb_short_event_0();
  i_err |= main_dvb_short_event_1();
  i_err |= main_dvb_short_event_2();
  i_err |= main_dvb_tshifted_ev_();
  i_err |= main_dvb_stream_identifier_();
  i_err |= main_dvb_ca_identifier_();
  i_err |= main_dvb_content_();
  i_err |= main_dvb_parental_rating_();
  i_err |= main_dvb_teletext_();
  i_err |= main_dvb_local_time_offset_();
  i_err |= main_dvb_subtitling_();
  i_err |= main_dvb_terr_deliv_sys_();

  if(i_err)
    fprintf(stderr, "At least one test has FAILED !!!\n");
  else
    fprintf(stdout, "All tests succeeded.\n");

  return i_err;
}

